bases:
  - ../../bases/repositories.yaml

releases:
  - name: postgres
    namespace: postgres
    chart: bitnami/postgresql
    version: ~18.0.0
    values:
      - values.yaml
    hooks:
      - events: ["presync"]
        showlogs: true
        command: "kubectl"
        args:
          - "apply"
          - "-f"
          - "namespace.yaml"
      - events: ["presync"]
        showlogs: true
        command: "kubectl"
        args:
          - "apply"
          - "-f"
          - "sealed-secret.yaml"
