---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-credentials
  namespace: postgres
spec:
  encryptedData:
    password: AgBWfibXAuXCparoxeqdX2nRYv/ad8pgS1mSyPO+tb7nt/QxSvPeEnQclENRnsyzASrVaghOJZd5vBT3R/ccAemIYBBGsqdVrHtW9YP8LLI7DKyapn9F0zQhQ+LRGSquZqPbGq40Bc/KLjDrIsk6qFZkjU1wcUP7JC8vDdYeAsdVp4jQPoD+GH6Is0G1T21uqZkiUUVYhgMW/4V3dEoZPkgd51x3Gh9KzlniV+/wVVMni+fIbFZvtQO2XgNp7rtBFVLnbD7sIo7NXGvGH9BucznRtcAnV2RYyvp/Vheo+/dSD/WYqH2okQhC24Ugi6/X7Qh4YQmiLjyUnkmmLO473XxUxBzCWKAGWC/rflUF9nVesYa8ijnSw0aXdg5GDz2odFmu4zcZfpZ7EtI260GVHWiStpBL77ZcLagUiZByNTFF7HdYfx8ejpaJTNe5xHnbgnDsBqUyAIqwZir/lyyG1rOrWN2ZTsbzDCJ8tyYE+dk9194Vm1Bn/Ao/XEXwNOxBnMQF76WAQihPBLtkheagymbK5KWjFtY0DrjtCRmQDCmAvnsKTw7CIKFdhTrllggYK0ulMAimaAyjLcvyJ3e9OsrRvkSQ21UCb0SwUsIo53rC5bmOHWhbyCjwCci6g2pHrqjlmXBh5vEW1Ea4FA6dOCeRl+b3fzwVPI4vfx2Z3nuGMm8TF+RHUzeh+TF07ZJUsvzUxCgod/BmjyGMoz6+yiW/17O9VqVa43TxFIk1xac=
    postgres-password: AgAxjg5QqCA1t/o2rQW/wwUxqJFit6elMPtCT802HJCKyR9sP8JgV8rW0pn2CFQekL79gv3dSp4K2XjtV0n+DXhqcyYp/KsmqP9LyiNtwrlboynqUhq1u6Hlyy9cQVr1mbLnx7U+/vT08gWB+JOqY99db1FwueqTMHSAwdDKblT6a7JwNug0NYFbNWyM9OHVHyGGVVDSlsD1PvS2R4pVpahhn9/kseuB8vmNRIntTMMsjoOEfPINXmgpFnk+YAACkKjE5kcMx7jdBRukjDoronNt/srOvZF9jkgyc01lCSmC3pPMF4trhhC+QtLM4189rfz+PYbtnRltGx7hsCRo0OIZDIOua/NX5XIWM+KRig+dq33cy7zlBNnxBd2XnpWHLCAzqFzONJCAy2YvmMxK53DMKKoahCyZ4JtkGIftbC+GVhW2jFLY4UesLxc4JaL+LWq4VmIxskWcjC5bUIRKqegGbZpTvG9H3kBsDb6AKnYctzpaweMJtitCeEk4tK7jUrKQOfyao4cukLM5IValzh0sq4A7QEKfz37N/+Glexi9Xh4qiUFnKRlFAGClVjlzYNalGfoLo7hbXl+RUTTs8KWSuXnKSNc0SBB/9pNgr+9P1L5IwqDMTmPfZc4k62n2W5/y8e1/8URyg3OslIS42bdrooBxi14EKkzC8Eri4nv7LEZzg+8qVpEI118NVaqzLucp+WQeoD1aUmJPRxjW6/GSFkOBmT+xVXGVuzqx5iA=
  template:
    metadata:
      name: postgres-credentials
      namespace: postgres
    type: Opaque
