---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: coder-credentials
  namespace: coder
spec:
  encryptedData:
    pg-connection-url: AgAoqsjffg7e1vHtBHHx8RZ4vGSASW28WgvkMpReqLjXl9Ezqw1tjkqFnP8QhBAbFvSq5323L8wQQcIBRpfn8QEbsQSFzfm6k+wmTmk5gMxhawMSM8BSY92M9CGpwquMFUq3puQjY38lh7wtPG4Qvrd2kFkxTuKnOGTJUZuFLlsq8lurtyz6Y+z/HB7cZ8RDkyYW9TVIAFjnY+aGuFKrHCyszFbP3D64czjDFiaEg+PXnO2/OIzLwUfmNFosTJpzSwtV4EzL+3hKVMkFEk0tv8v1mJkmNDO+gkhVFYtePA1KojoIWJBzRYVDFPeo8WjqKMPi6T5fMH3kypEYNqgi8FWs9JZ+H19/Hw/feHqqySSPhtRd4sS2jx3Etm26DczO+796MjFigJjkQSO8TT5UIcv7qk8GjdWfR7bjSQjKT5CweDD7IPNeY/0VE+m+XdWFULeOwuUgPGD7GsPI4J7qFOiHz/o3CkHVa03uYMp4UGAOQZmGh7sdQqCTfA+wvZoheHuAj4nvRoK51Mq8tXvDe3u7HsnEtNzHVu+B4Zbr3G3ETojbBYX488/QxAp4WHX9ct7QBdkmTaSa7DeTAvTw4dK6nQXpeoNNSFr89lyiKMVmj09zn0X1U2zkqaNzTCuW+fA3UDZhyA9qUEU0Nta8EMgImOQEhuKKU/iBp/6SLCA5qkT+ntFz5WSv7//VHtK47mDZ0VmIehs+JbWicHIit20YOaULaD79WlasUJ4m5V8Cg7NhWYAZKV/UVkYqxR1PHaFnd0SxEpv7Yrs3ddKjx3VZ1hDN6jZ59Hq4aqZZRNnqSc2Ayx6QVkFPvjoxi4t27+ZQ8K1PTqsbbupYj84uQXvfCwKyApqcVWKg
  template:
    metadata:
      name: coder-credentials
      namespace: coder
    type: Opaque
