apiVersion: v1
kind: Secret
metadata:
  name: coder-credentials
  namespace: coder
type: Opaque
stringData:
  pg-connection-url: "postgres://coder:<password>@postgres-postgresql.postgres.svc.cluster.local:5432/coder?sslmode=disable"
